### ISSUE TITLE
Swagger2에서 TripGroup create 요청시 415 에러가 나는 문제

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_BE#57]
**이슈 사항**
1. 문제점 발생
현재 `/swagger-ui.html` 에서 TripGroupController 부분 create 요청시 415 에러가 납니다.
해당 사항을 확인해 보니 현재 저희 서비스에서 사용하고 있는 Swagger2 에서 문제가 있는 걸로 파악중입니다. 
- 파일과 함께 Request Body를 요청하면 body에 있는 content-type이 `octet-stream`으로 고정되어 요청이 오는 것 같습니다.
- 참조: [springdoc/springdoc-openapi 이슈](https://github.com/springdoc/springdoc-openapi/issues/460)

2. 해결 방법
postman에서 body → form-data → content-type을 `application/json`으로 명시 후 요청을 보내면 정상적으로 응답합니다.

3. 예정
마지막 기능 수정[028] 이후 Swagger2를 Swagger3로 버전을 변경해보려고 합니다.

---

**배경**
1. 어느 환경(배경)에서 문제가 발생했는지 간략히 적어주세요. (e.g. MySql, H2, SpringSecurity)
swagger2

**Comment by wooooozin** [comment]
<img width="757" alt="스크린샷 2023-11-16 오전 6 57 42" src="https://github.com/ValueWith/ValueWith_BE/assets/95316662/c0c0e253-edaa-4152-89a4-9da0bdce4c43">
requestDto를 ModelAttribute 어노테이션으로 변경하니 415 에러는 없지만
ModelAttribute 사용 시 프론트에서 application/json 요청을 multipart/form-data로 변경해야 합니다.

현재 tripDate가 문자열로 들어와서 이와 관련된
Cannot invoke "java.time.LocalDate.minusDays(long)" because the return value of "com.valuewith.tweaver.group.dto.TripGroupRequestDto.getTripDate()" is null
발생합니다.

**Comment by eod940** [comment]
네 확인했습니다. 3.0으로 변경해봤는데 3.0으로 바꾼다고 변경이 되는건 아닌 것 같습니다 ㅠㅠ
